config/routes.rb
Rails.application.routes.draw do
  root to: 'site#home'

  match '/twilio', to: 'twilio#index', via: %i[post]

  devise_for :users, controllers: { registrations: 'users/registrations' } #match '/users', to: 'users#edit', via: %i[get]

  resources :activities
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :date, presence: true
  validates :duration, presence: true
  validates :rating, presence: true
  validates :user_id, presence: true

  enum rating: { awful: 0, bad: 1, neutral: 2, good: 3, excellent: 4 }

  enum name: {
         running: 0,
         swimming: 1,
         biking: 2,
         badminton: 3,
         basketball: 4,
         boxing: 5,
         fitness: 6,
         football: 7,
         gymnastic: 8,
         judo: 9,
         motorbiking: 10,
         rugby: 11,
         tennis: 12,
         yoga: 13
       }

  def kcal
    {
      'swimming' => 7,
      'running' => 10,
      'biking' => 8,
      'badminton' => 6,
      'basketball' => 7,
      'boxing' => 8,
      'fitness' => 9,
      'football' => 7,
      'gymnastic' => 4,
      'judo' => 9,
      'motorbiking' => 6,
      'rugby' => 7,
      'tennis' => 13,
      'yoga' => 3
    }[
      name
    ] * duration
  end

  def self.dist(_name)
    {
      'swimming' => true,
      'running' => true,
      'biking' => true,
      'badminton' => false,
      'basketball' => false,
      'boxing' => false,
      'fitness' => false,
      'football' => false,
      'gymnastic' => false,
      'judo' => false,
      'motorbiking' => true,
      'rugby' => false,
      'tennis' => false,
      'yoga' => false
    }[
      _name
    ]
  end

  def dist
    Activity.dist(name)
  end

  def has_dist
    dist && !distance.blank? ? true : false
  end

  def pace
    has_dist ? distance / duration : 0
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_activity, only: %i[show edit update destroy]
  helper_method :sort_column, :sort_direction, :filter_by, :since

  # GET /activities
  def index
    @all_activities = Activity.all.where(user: current_user)
    @chart_activities = @all_activities.where(name: filter_by, date: since)
    @activities =
      if sort_column != 'kcal'
        @chart_activities.order("#{sort_column} #{sort_direction}")
      else
        @chart_activities.sort_by do |a|
          a.kcal * (sort_direction == 'asc' ? 1 : -1)
        end
      end
  end

  # GET /activities/1
  def show
    @comparable_activities =
      Activity.all.where(
        user: current_user,
        name: @activity.name,
        date: '0001-01-01 00:00:00'..@activity.date.to_datetime
      )
    @previous_activity = @comparable_activities.where.not(id: @activity.id).last
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit; end

  # POST /activities
  def create
    @user = User.find(current_user.id)
    @activity = @user.activities.create(activity_params)
    unless @activity.date.blank?
      # We can omit that for now, the form will throw an error anyway!
      @activity.date =
        DateTime.new(
          @activity.date.year,
          @activity.date.month,
          @activity.date.day,
          Time.now.hour,
          Time.now.min,
          Time.now.sec,
          Time.now.zone
        )
    end

    respond_to do |format|
      if @activity.save
        format.html do
          redirect_to @activity, notice: 'Activity was successfully created.'
        end
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json do
          render json: @activity.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /activities/1
  def update
    respond_to do |format|
      # Update date manipulation intended to maintain original creation time
      p_date =
        activity_params[:date].to_date
      updated_date =
        DateTime.new(
          p_date.year,
          p_date.month,
          p_date.day,
          @activity.date.hour,
          @activity.date.min,
          @activity.date.sec,
          @activity.date.zone
        )
      if @activity.update(activity_params) &&
           @activity.update_attribute(:date, updated_date)
        format.html do
          redirect_to @activity, notice: 'Activity was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json do
          render json: @activity.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /activities/1
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html do
        redirect_to activities_url,
                    notice: 'Activity was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private # Use callbacks to share common setup or constraints between actions.
  def set_activity
    @activity = Activity.find(params[:id])
    unless current_user.id == @activity.user_id
      redirect_to activities_url, alert: 'Unauthorized access!'
    end
  end

  # Only allow a list of trusted parameters through.
  def activity_params
    params.require(:activity).permit(
      :name,
      :date,
      :duration,
      :rating,
      :distance
    )
  end

  def since
    if params[:since]
      params[:since].to_date..Float::INFINITY
    else
      -Float::INFINITY..Float::INFINITY
    end
  end

  def filter_by
    if Activity.names.include?(params[:by])
      Activity.names[params[:by]]
    else
      0..Float::INFINITY
    end
  end

  def sort_column
    if Activity.column_names.include?(params[:sort])
      params[:sort]
    else
      params[:sort] == 'kcal' ? 'kcal' : 'date'
    end
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'desc'
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def add_chevron(dir)
    if dir == 'up'
      awesome('fas fa-chevron-up')
    else
      dir == 'down' ? awesome('fas fa-chevron-down') : awesome('fas fa-equals')
    end
  end

  def compare_performance
    unless !@activity.has_dist || !@previous_activity.has_dist
      raw(
        'You went through <strong>' +
          (
            if (@activity.distance > @previous_activity.distance)
              'longer' + add_chevron('up')
            elsif (@activity.distance < @previous_activity.distance)
              'shorter' + add_chevron('down')
            else
              'the same' + add_chevron('equal')
            end
          ) + '</strong>distance at a <strong>' +
          (
            if (@activity.pace > @previous_activity.pace)
              'faster' + add_chevron('up')
            elsif (@activity.pace < @previous_activity.pace)
              'slower' + add_chevron('down')
            else
              'similar' + add_chevron('equal')
            end
          ) + '</strong>speed'
      )
    end
  end

  def compare_rating
    if @activity.rating > @previous_activity.rating
      raw('Better <strong>feeling</strong>') + add_chevron('up')
    elsif @activity.rating < @previous_activity.rating
      raw('Worse <strong>feeling</strong>') + add_chevron('down')
    else
      raw('Same <strong>feeling</strong>') + add_chevron('equal')
    end
  end

  def compare_duration
    if @activity.duration > @previous_activity.duration
      raw('<strong>Longer</strong> time workout') + add_chevron('up')
    elsif @activity.duration < @previous_activity.duration
      raw('<strong>Shorter</strong> time workout') + add_chevron('down')
    else
      raw('<strong>Same</strong> time workout') + add_chevron('equal')
    end
  end

  def print_pace
    if @activity.pace != 0
      number_with_precision(@activity.pace, precision: 3)
    else
      'N/A'
    end
  end

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction =
      column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to title,
            {
              sort: column,
              direction: direction,
              since: request.params['since'],
              by: request.params['by']
            },
            { class: css_class } #link_to title, { sort: column, direction: direction }, data: { turbolinks: false }, class: css_class
  end

  # Random quote provider
  def random_quote
    json = JSON.load File.open 'app/assets/quotes.json'
    r = rand(json.count)
    if json[r]['author'].blank?
      "\"#{json[r]['text']}\""
    else
      "\"#{json[r]['text']}\" - #{json[r]['author']}"
    end
  end
end

app/views/activities/_form.html.erb
<div class="new-activity-wrapper">

    <%= form_with(model: activity, local: true) do |f| %>

      <h2>What did you do?</h2>
      <div class="form-group activities">
        <% Activity.names.keys.each do |name| %>
          <%= f.label name do %>
            <%= f.radio_button :name, name, :checked => (activity.name.blank? ? name == Activity.names.keys.first : name == activity.name), "onchange" => "adjustForm(#{Activity.dist(name)})" %>
            <%= image_tag "128/#{name}.png", width: '100', height: '100', alt: name, "data-toggle" => "tooltip", "data-placement" => "bottom", "title" => name.humanize %>
          <% end %>          
        <% end %>
      </div>

      <h2>When was it?</h2>
      <div class="form-group row date-wrapper">
        <div class="special-row">
          <%= f.label :date, :class => 'col-form-label' %>
          <%= f.date_field :date, :value => activity.date.blank? ? Time.now.strftime('%Y-%m-%d') : activity.date.strftime('%Y-%m-%d'), :class => "form-control date-picked" %>
        </div>
        <div class="special-row">
          <%= f.label :duration, :class => 'col-form-label' %>
          <%= f.number_field :duration, min: 1, :class => "form-control number" %>
          <%= f.label "minutes", "minutes", :class => 'col-form-label secondary' %>  
        </div>
        <div class="special-row">
          <div class="row distance-wrapper">
            <%= f.label "total", :class => 'col-form-label' %>
            <%= f.number_field :distance, :step => "0.01", :class => "form-control number" %>
            <%= f.label "km", "km", :class => 'col-form-label secondary' %>
          </div>
        </div>
      </div>
 
      <h2>How did you feel?</h2>
      <div class="form-group row rating">
        <% Activity.ratings.keys.each do |rating| %>
          <div class="rating custom-control custom-radio">
            <%= f.radio_button :rating, rating, :id => rating, :class => "custom-control-input #{error_class(activity, :rating)}" %>
            <%= f.label rating, "for" => rating, :class => "custom-control-label" %>
          </div>          
        <% end %>
      </div>

      <div class="submit-wrapper">
        <% unless activity.name.blank? %>
          <%= link_to activity, method: :delete do %>
            <button type="button" class="btn btn-secondary btn-delete-activity">Delete</button>
          <% end %>
        <% end %>

        <%= f.submit "Submit", :class => 'btn btn-primary submit' %>
      </div>
    <% end %>

  </div>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>
<div class="navigation-links">
    <%= link_to 'Back', activities_path, :class => "back" %> 
    <span class="separator">|</span>
    <%= link_to 'Show', @activity %>
</div>

<%= render 'form', activity: @activity %>

app/views/activities/index.html.erb
<h1>Dashboard</h1>

<div class="random-quote-wrapper" >
  <p class="lead quote"><%= random_quote %></p>
</div>

<%= button_to "+ New activity", new_activity_path, method: :get, :form_class => 'to-new-activity', :class => 'btn btn-primary' %>

<h2>My activities</h2>
<div class="form-group row activities-filter-wrapper">
  <%= label_tag "filter by", nil, class: 'col-form-label' %>
  <%= select_tag "filter", options_from_collection_for_select(@all_activities.select(:name).distinct, :name, "name", params[:by]), :include_blank => true, class: "form-control activity-filter", :onchange => "activitiesFilterByName()" %>
  <%= label_tag "since", "since", class: 'col-form-label' %>
  <%= date_field_tag "filter-since", params[:since], class: 'form-control date-picked', :onchange => "activitiesFilterByDate()" %>
</div>

<% if params[:by] %>
  <%= area_chart @chart_activities.group_by_day(:date).sum(:duration), discrete: true %>
<% else %>
  <%= pie_chart @chart_activities.group(:name).sum(:duration) %>
<% end %>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col"><%= sortable "date" %></th>
      <th scope="col"><%= sortable "name" %></th>
      <th class="thead-duration" scope="col"><%= sortable "duration", "Duration (min)" %></th>
      <th scope="col"><%= sortable "kcal" %></th>
      <th scope="col"><%= sortable "rating", "Feeling" %></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each_with_index do |activity, i| %>
      <% if (i + 1).even? %>
        <tr class="row-even">
      <% else %>
        <tr>
      <% end %>
        <th><%= i + 1 %></th>
        <td><%= activity.date.strftime('%Y-%m-%d') %></td>
        <td><%= link_to activity.name.humanize, activity %></td>
        <td><%= activity.duration %></td>
        <td><%= number_with_delimiter(activity.kcal, :delimiter => ',') %></td>
        <td><%= activity.rating.humanize %></td>
        <td>
          <%= link_to edit_activity_path(activity) do %>
            <%= awesome "far fa-edit" %>
          <% end %>
        </td>
        <td>
          <%= link_to activity, method: :delete do %>
            <%= awesome "far fa-trash-alt" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/activities/new.html.erb
<h1>New Activity</h1>
<div class="navigation-links">
    <%= link_to 'Back', activities_path, :class => "back" %>
</div>

<%= render 'form', activity: @activity %>

app/views/activities/show.html.erb
<h1><%= @activity.name.humanize %></h1>
<div class="navigation-links">
    <%= link_to 'Back', activities_path, :class => "back" %> 
    <span class="separator">|</span>
    <%= link_to 'Edit', edit_activity_path(@activity) %>
</div>

<div class="activity-wrapper">
    <h2 class="headline">Highlights</h2>
    <p>Performed the <strong><%= @activity.date.strftime("%d of %B, %Y") %></strong><p>
    <p>You felt <strong><%= @activity.rating %></strong> during your <strong><%= @activity.duration %></strong> minutes workout</p>
    <p>Estimated calories consumption of <strong><%= number_with_delimiter(@activity.kcal, :delimiter => ',') %></strong> KCal</p>
    <% if @activity.has_dist %>
        <p>Traveled distance of <strong><%= @activity.distance %></strong> km at an average pace of <strong><%= print_pace %></strong> km/minute</p>
    <% end %>

    <h2 class="headline">Comparison</h2>
    <% if @comparable_activities.count <= 1 %>
        <p>This is your first <%= @activity.name %> workout, <strong>congratulations</strong>!</p>
    <% else %>
        <p><%= compare_rating %></p>
        <p><%= compare_duration %></p>
        
        <% logger.info ">>>>>>>>" %>
        <% logger.info @comparable_activities.group_by_day(:date).map{ |a| [a.date.to_date, a.pace]}.to_h %>
        <% logger.info @comparable_activities.group_by_day(:date).map{ |a| [a.date.to_date, a.pace]}.push([:id, 'y1']).to_h %>

        <% if @activity.has_dist %>
            <p><%= compare_performance %></p>
            <%= column_chart [
            {name:"distance", data: @comparable_activities.group_by_day(:date).sum(:distance)}, 
            {name:"duration", data: @comparable_activities.group_by_day(:date).sum(:duration)},
            {name:"pace", data: @comparable_activities.group_by_day(:date).map{ |a| [a.date.to_date, a.pace]}}
        ], library: { legend: { position: 'top' }, series: { 0 => {targetAxisIndex: 0 }, 1 => {targetAxisIndex: 0 }, 2 => {targetAxisIndex: 1} }} %>
        <% else %>
            <%= column_chart @comparable_activities.group_by_day(:date).sum(:duration), xtitle:"Duration", discrete: true %>
        <% end %>
    <% end %>
</div>