config/routes.rb
Rails.application.routes.draw do
  root to: 'site#home'

  match '/twilio', to: 'twilio#index', via: %i[post]

  devise_for :users, controllers: { registrations: 'users/registrations' } #match '/users', to: 'users#edit', via: %i[get]

  resources :activities
end

app/views/layouts/_footer.html.erb
<footer id="footer" class="page-footer">
    <div class="container">
        <div class="row">

            <div class="col-md-3">
                <h3 class="font-weight-bold mt-5 mb-3">Move & Groove</h3> 
            </div>

            <div class="col-md-3">
                <h5 class="font-weight-bold text-uppercase mt-5 mb-3">Links</h5>
                <ul class="list-unstyled text-uppercase">
                    <li><%= link_to "Home", root_path %></li>
                    <li><%= link_to "Dashboard", activities_url %></li>
                    <li><%= link_to "How it works", root_path(:anchor => "learn-more") %></li>
                    <li><%= link_to "Log in", new_user_session_path %> | <%= link_to "Sign up", new_user_registration_path %></li>
                </ul>
                <hr class="clearfix w-100 d-md-none">
            </div>

            <div class="col-md-3">
                <h5 class="font-weight-bold text-uppercase mt-5 mb-3">Follow us</h5>
                <ul class="socials list-unstyled text-uppercase">
                    <li>
                        <%= awesome "fa fa-facebook-square" %>
                        <%= link_to "Facebook", "https://www.facebook.com/" %>
                    </li>
                    <li>
                        <%= awesome "fab fa-instagram" %>
                        <%= link_to "Instagram", "https://www.instagram.com/" %>
                    </li>
                    <li>
                        <%= awesome "fa fa-twitter-square" %>
                        <%= link_to "Twitter", "https://www.twitter.com/" %>
                    </li>
                    <li>
                        <%= awesome "fa fa-youtube-play" %>
                        <%= link_to "Youtube", "https://www.youtube.com/" %>
                    </li>
                </ul>
            </div>

            <div class="col-md-3">
                <h5 class="font-weight-bold text-uppercase mt-5 mb-3">Contact</h5>
                <ul class="list-unstyled text-uppercase">
                    <li>
                        <%= mail_to "support@moveandgroove.com", name="Support" %>
                    </li>
                    <li>
                        <%= link_to "Phone", "tel:+1(666)123456" %>
                    </li> 
                </ul>

                <h5 class="font-weight-bold text-uppercase mt-4 mb-3">More</h5>
                <ul class="list-unstyled text-uppercase">
                    <li><%= link_to "Terms and conditions", root_path %></li>
                    <li><%= link_to "Privacy policy", root_path %></li>
                </ul>
            </div>
        </div>

        <hr/>
        <div class="footer-copyright text-center pb-3">
            © 2020 Copyright <a href="#">Move & Groove.</a> All rights reserved.
        </div>

    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-primary">
  <div class="container">
    <%= link_to "Move & Groove", root_path, :class => 'navbar-brand' %>
    <span class="navbar-text">Keep moving!</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Home", root_path, :class => 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Dashboard", activities_url, :class => 'nav-link' %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item login-item">
            <%= link_to current_user.email.split('@')[0].capitalize(), edit_user_registration_path, :class => 'nav-link' %> 
          </li>
          <li class="nav-item separator">|</li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, :class => 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item login-item">
            <%= link_to "Log in", new_user_session_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item separator">|</li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link' %> 
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Move & Groove - Fitness tracker</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8" />
    <meta name="turbolinks-cache-control" content="no-cache">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="index, follow" />
    <meta name="theme-color" content="#000000" />
    <meta name="author" content="Kévin Renier">
    <meta
      name="description"
      content="Move & Groove is a fitness tracker platform to easily record your workout performance! Kévin Renier Development project. Built using Bootstrap, Ruby on Rails and Twilio WhatsApp API."
    />
    <meta name="keywords" content="Kévin Renier; Portfolio; Product manager; Geneva; Developer; Frontend developer; Fitness tracker; API; Performance;" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', 'data-turbolinks-preview': false %>
    <link rel="preconnect" href="https://kit.fontawesome.com" />
    <link rel="preconnect" href="https://www.gstatic.com" />
    <link rel="alternate" hrefLang="x-default" href="https://moveandgroove.thekecha.com" />
    <%= favicon_link_tag asset_path('favicon.png') %>
    <%= javascript_include_tag 'https://kit.fontawesome.com/7967897a07.js', async: true %>
    <%= javascript_include_tag 'https://www.gstatic.com/charts/loader.js', async: false %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <% if notice %>
      <div class="alert alert-success">
        <div class="container">
          <%= notice %>
        </div>
      </div>
    <% end %>
    
    <% if alert %>
      <div class="alert alert-danger">
        <div class="container">
          <%= alert %>
        </div>
      </div>
    <% end %>

    <a href="#" class="back-to-top"></a>
    
    <% if current_page?(root_path) %>
      <%= yield %>
    <% else %>
      <div class="container app-container">
        <%= yield %>
      </div>
    <% end %>
    
    <%= render "layouts/footer" %>

  </body>
</html>